### ISSUE TITLE
Connector configuration missing in the documents

### ISSUE THREAD

**Issue by mgobec** [smartcat-labs/cassandra-diagnostics#197]
Connector configuration missing in the documents. It is required that connector can connect over JMX to initialize info provider.

```
connector:
  jmxHost: 10.0.0.1
  jmxPort: 8888
  jmxAuthEnabled: true
  jmxUsername: username #Optional
  jmxPassword: password #Optional
```
